[build]
target = "wasm32-unknown-unknown"
rustflags = [
    '-Ctarget-feature=+atomics,+bulk-memory,+mutable-globals',
    '-Clink-args=--shared-memory',
    '-Clink-args=--max-memory=1073741824',
    '-Clink-args=--import-memory',
    '-Clink-args=--export=__wasm_init_tls',
    '-Clink-args=--export=__tls_size',
    '-Clink-args=--export=__tls_align',
    '-Clink-args=--export=__tls_base',
]

[unstable]
build-std = ['std', 'panic_abort']
